### ISSUE TITLE
uninstall removes the configuration file

### ISSUE THREAD

**Issue by marbx** [marbx/salt-windows-msi#1]
uninstall removes the configuration file (```salt/conf/minion```)

**Comment by marbx** [comment]
I assume the config file is part of the instllation.
uninstall removes all parts of the installation.

I need to specify, that `salt/conf/minion` must not be removed.

**Comment by markuskramerIgitt** [comment]
Do I use "<file id"?



salt-windows-msi\wix\MinionMSI\dist-amd64.wxs
is the only file with "<file id" in it
Who creates it?
Why has each file its own component?
Does this slow down uninstall?

**Comment by marbx** [comment]
Remove the GUID of the component.

**Comment by marbx** [comment]
Need optional removal

**Comment by marbx** [comment]
Opening another issue
