### ISSUE TITLE
Maybe replace nssm.exe with python.exe in Service

### ISSUE THREAD

**Issue by marbx** [marbx/salt-windows-msi#32]
This python.exe Minion replies to the master:

```
C:\salt\bin>python.exe Scripts\salt-minion -c ..\conf -l quiet
```
`<ServiceInstall>` is in https://github.com/markuskramerIgitt/salt-windows-msi/blob/master/wix/MinionMSI/servicePython.wxs
The installer hangs forever, cancel manually.

Error from Event Viewer, Windows Log, System:
```
The service did not respond to the start or control request in a timely fashion.
```

After Googling python as windows service 
maybe class DataTransToMongoService(win32serviceutil.ServiceFramework)

**Comment by marbx** [comment]
---

**Comment by markuskramerIgitt** [comment]
nssm



WriteRegistryValues: Key: \System\CurrentControlSet\Services\salt-minion\Parameters\AppExit, Name: , Value: Restart
MSI (s) (28:44) [21:08:47:493]: Executing op: ActionStart(Name=InstallServices,Description=Installing new services,Template=Service: [2])
Action 21:08:47: InstallServices. Installing new services
MSI (s) (28:44) [21:08:47:494]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (28:44) [21:08:47:494]: Executing op: ServiceInstall(Name=salt-minion,DisplayName=Salt Minion,ImagePath=C:\salt\nssm.exe,ServiceType=16,StartType=2,ErrorControl=32769,,Dependencies=nsi[~][~][~],,StartName=LocalSystem,Password=**********,Description=Salt Minion from saltstack.com,,)
InstallServices: Service: 
MSI (s) (28:44) [21:08:47:565]: Executing op: ActionStart(Name=MsiConfigureServices,,)
Action 21:08:47: MsiConfigureServices. 
MSI (s) (28:44) [21:08:47:566]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (28:44) [21:08:47:566]: Executing op: ServiceConfigure(,Name=salt-minion,Event=5,ConfigType=3,Argument=0)
MSI (s) (28:44) [21:08:47:567]: Changing configuration of service salt-minion.
MSI (s) (28:44) [21:08:47:581]: Changed configuration of service salt-minion with ConfigType SERVICE_CONFIG_DELAYED_AUTO_START_INFO
MSI (s) (28:44) [21:08:47:581]: Done changing configuration of service salt-minion
MSI (s) (28:44) [21:08:47:581]: Executing op: ActionStart(Name=CAC.SetMaster,,)
Action 21:08:47: CAC.SetMaster. 
MSI (s) (28:44) [21:08:47:583]: Executing op: CustomActionSchedule(Action=CAC.SetMaster,ActionType=3073,Source=BinaryData,Target=SetMaster,CustomActionData=MasterHostname=78.47.109.196;MinionRoot=C:\salt\)
MSI (s) (28:CC) [21:08:47:587]: Invoking remote custom action. DLL: C:\windows\Installer\MSI946A.tmp, Entrypoint: SetMaster
MSI (s) (28:C8) [21:08:47:587]: Generating random cookie.
MSI (s) (28:C8) [21:08:47:602]: Created Custom Action Server with PID 4688 (0x1250).
MSI (s) (28:20) [21:08:47:652]: Running as a service.
MSI (s) (28:20) [21:08:47:653]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
SFXCA: Extracting custom action to temporary directory: C:\windows\Installer\MSI946A.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action MinionConfigurationExtension!MinionConfigurationExtension.MinionConfiguration.SetMaster

**Comment by marbx** [comment]
## Maybe ##

https://github.com/saltstack/salt/blob/develop/salt/utils/saltminionservice.py,

```
C:\salt\bin\python.exe C:\salt\bin\Lib\site-packages\salt\utils\saltminionservice.py -c C:\salt\conf -l quiet
Install ok
(1053, 'StartService', 'The service did not respond to the start or control request in a timely fashion.')

```
In Computer Management, Event Viewer, Windows Logs, System:

```
A service was installed in the system.

Service Name:  Salt Minion
Service File Name:  "C:\salt\bin\lib\site-packages\win32\PythonService.exe"
Service Type:  user mode service
Service Start Type:  auto start
Service Account:  LocalSystem
```
saltminionservice.py creates a service.

c:\salt\bin\Lib\site-packages\win32\Demos\service\ nativePipeTestService.py is an example of a service hosted by python.exe rather than pythonservice.exe.


To remove this (non-functional service)  `sc delete salt-minion` (reboot).
