### ISSUE TITLE
Christoph says: DefaultDirectory=INSTALLFOLDER

### ISSUE THREAD

**Issue by marbx** [marbx/salt-windows-msi#36]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa372064(v=vs.85).aspx
?

**Comment by markuskramerIgitt** [comment]
?Is this https://msdn.microsoft.com/en-us/library/windows/desktop/aa368295%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
?
