### ISSUE TITLE
Observed once: Another application has exclusive access to the file 'C:\salt\var\log\salt\minion

### ISSUE THREAD

**Issue by marbx** [marbx/salt-windows-msi#40]
Error 1306. Another application has exclusive access to the file 'C:\salt\var\log\salt\minion'.  Please shut down all other applications, then click Retry.

**Comment by marbx** [comment]
with /x /qb! and /x /qn

Stop salt-minion service first

Why did this work before?


Quirk fix  https://github.com/markuskramerIgitt/salt-windows-msi/commit/9ec89293b270725ae2fff04c396843e91753ec19


Seems fixed with https://github.com/markuskramerIgitt/salt-windows-msi/commit/9b6fbe6c8b69c195126c32f5b78582ee21b7764b

**Comment by markuskramerIgitt** [comment]
probably needs solution for https://github.com/markuskramerIgitt/salt-windows-msi/issues/32

**Comment by marbx** [comment]
---

**Comment by marbx** [comment]
several python.exe processes lingering without the salt-minion service prevented deletion of the file above

**Comment by marbx** [comment]
I assume we need to stop all minion processes

**Comment by marbx** [comment]
Fxied by https://github.com/markuskramerIgitt/salt-windows-msi/commit/c9be74be43fb7a86f0d69637c3734d3b7506a29b
