### ISSUE TITLE
Must get version equal to `salt --version`

### ISSUE THREAD

**Issue by marbx** [marbx/salt-windows-msi#49]
Which git commands one must execute to download and print the correct version?

`git describe` reports higher commit counts (lesser minor version, 4th version number) than `salt --version`

Function `__discover_version()`  in `version.py` uses many parameters:
```
$ git checkout 2016.11
$ git describe --tags --first-parent --match v[0-9]* --always
    v2016.11.1-96-g4913c4f
$ git describe
    v2016.11.1-444-g4913c4f
```
Even worse, the minor point (third version number) can differ:
```
$ git checkout 2016.11
$ git describe --tags --first-parent --match v[0-9]* --always
v2016.11.2-71-g99bfa7d
$ git describe
v2016.11.1-707-g99bfa7d
```
The minor point (third version number) is 2 or 1, while 3 has already been published/released. 
How do I get minor point relase 3?

Which git command must I use to retrieve exactly the offical 2016.11.3 release?

rallytime writes at https://github.com/saltstack/salt/pull/34535#issuecomment-273550951
The last comment I have is that it would be good to mention that all of these sections with the various git tags are relative to your local git fetch. The salt --version command (and hence git checkout) looks for the most recent recognized tag on the system, which may not necessarily be the most recent tag up on GitHub.

**Comment by rallytime** [comment]
Hi @markuskramerIgitt - So the reason you can't find anything for 2016.11.3 is because that hasn't been released yet. :)

We only recently published the 2016.11.2 tag a couple of weeks ago. Does that help?

**Comment by marbx** [comment]
Hi @rallytime, yes, I understand.
I just looked at (the index) https://docs.saltstack.com/en/latest/topics/releases, and the release notes for 11.3 are empty.
Thank you!

**Comment by marbx** [comment]
Hi @rallytime,
I should stop thinking about `git describe` and leave it warm and save in `version.py`:

```
C:\git\salt\salt>git checkout 2016.11
C:\git\salt\salt>\Python27\python.exe version.py
2016.11.2-72-g7611698
```

Is `git checkout 2016.11` what I should execute before building the minion?

**Comment by rallytime** [comment]
> I just looked at (the index) https://docs.saltstack.com/en/latest/topics/releases, and the release notes for 11.3 are empty.

Ah, yes. We add the release notes file for the upcoming release right after we publish the current release. That way it is easy for contributors to add anything to the release notes for the upcoming release.

> Is git checkout 2016.11 what I should execute before building the minion?

That kind of depends on what commit you want your release to be built off of. If you do `git checkout 2016.11`, that checks out the 2016.11 branch.

If you want to build your release off of one of our release tags (which is I think what you're asking), you need to checkout the specific tag by doing: `git checkout v2016.11.2` (or whichever tag you're trying to build; v2016.11.2 is just an example of the latest tagged version of salt).

Does that help?

**Comment by marbx** [comment]
Hi @rallytime,
thank you, I realise I keep repeating the same question :-)
Hopefully I will remember next time before I ask you.
I just checked out the 2016.11 branch, and the v2016.11.2 tag, which causes a note about a detatched head.

Could you also help me with a Python problem in PR https://github.com/saltstack/salt/pull/39274? 
I struggle to retrieve the version information from inside salt/salt/python.py

**Comment by marbx** [comment]
tested with 2016.11.2-104-ge4c7168
