### ISSUE TITLE
When to change the product Id

### ISSUE THREAD

**Issue by marbx** [marbx/salt-windows-msi#61]
https://support.firegiant.com/hc/en-us/articles/230912367-Upgrade-options

**Comment by markuskramerIgitt** [comment]
Salt Minion 2016.11.3   64      MsiExec.exe /X{28C82B6C-391A-4AA3-961E-2FFAD3D013C1}

**Comment by marbx** [comment]
Just always, as it was originally (@saxonww)  https://github.com/markuskramerIgitt/salt-windows-msi/commit/460609d13ac124a49aaa71a30ff1139287ecdc29
