### ISSUE TITLE
install default is not c:\salt but e:\salt

### ISSUE THREAD

**Issue by marbx** [marbx/salt-windows-msi#8]

**Comment by markuskramerIgitt** [comment]
I closed this .... mmmh

**Comment by marbx** [comment]
From     http://badecho.com/2008/12/the-root-of-the-problem/
If you don't define and set ROOTDRIVE in the property table of your installer database,
then the tool installing the product has to set the property.
How does it determine which drive to assign to ROOTDRIVE?
It simply looks at all available hard drives, and chooses the one with the most free space.

From https://docs.microsoft.com/en-us/windows/win32/msi/rootdrive
